export const defaultSchema = [
  {
    attr: 1157,
    canTrigger: true,
    code: 'switch_1',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power3',
    id: 24,
    mode: 'rw',
    name: '开关1',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1157,
    canTrigger: true,
    code: 'switch_2',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power3',
    id: 25,
    mode: 'rw',
    name: '开关2',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1157,
    canTrigger: true,
    code: 'switch_3',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power3',
    id: 26,
    mode: 'rw',
    name: '开关3',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 1157,
    canTrigger: true,
    code: 'switch_4',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power3',
    id: 27,
    mode: 'rw',
    name: '开关4',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 4096,
    canTrigger: true,
    code: 'scene_switch',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 104,
    mode: 'rw',
    name: '按键数量',
    property: {
      range: [
        'switch_1',
        'switch_2',
        'switch_3',
        'switch_4',
        'switch_5',
        'switch_6',
        'switch_7',
        'switch_8',
      ],
      type: 'enum',
    },
    type: 'obj',
  },
];
