export const defaultSchema = [
  {
    attr: 1856,
    canTrigger: true,
    code: 'switch_type_1',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '{"trigger":"direct"}',
    id: 1,
    mode: 'ro',
    name: '开关方式1',
    property: {
      range: ['single_click', 'double_click', 'long_press'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1856,
    canTrigger: true,
    code: 'switch_type_2',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '{"trigger":"direct"}',
    id: 2,
    mode: 'ro',
    name: '开关方式2',
    property: {
      range: ['single_click', 'double_click', 'long_press'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1856,
    canTrigger: true,
    code: 'switch_type_3',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '{"trigger":"direct"}',
    id: 3,
    mode: 'ro',
    name: '开关方式3',
    property: {
      range: ['single_click', 'double_click', 'long_press'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 1856,
    canTrigger: true,
    code: 'switch_type_4',
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: '{"trigger":"direct"}',
    id: 4,
    mode: 'ro',
    name: '开关方式4',
    property: {
      range: ['single_click', 'double_click', 'long_press'],
      type: 'enum',
    },
    type: 'obj',
  },
] as const;
