export const defaultSchema = [
  {
    attr: 128,
    canTrigger: true,
    code: 'switch_1',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 1,
    mode: 'rw',
    name: '开关1',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'countdown_1',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-dp_time2',
    id: 9,
    mode: 'rw',
    name: '开关1倒计时',
    property: {
      unit: 's',
      min: 0,
      max: 86400,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 704,
    canTrigger: true,
    code: 'add_ele',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 17,
    mode: 'ro',
    name: '增加电量',
    property: {
      min: 0,
      max: 50000,
      scale: 3,
      step: 100,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 704,
    canTrigger: true,
    code: 'cur_current',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 18,
    mode: 'ro',
    name: '当前电流',
    property: {
      unit: 'mA',
      min: 0,
      max: 30000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 704,
    canTrigger: true,
    code: 'cur_power',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 19,
    mode: 'ro',
    name: '当前功率采样',
    property: {
      unit: 'W',
      min: 0,
      max: 80000,
      scale: 1,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 704,
    canTrigger: true,
    code: 'cur_voltage',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 20,
    mode: 'ro',
    name: '当前电压采样',
    property: {
      unit: 'V',
      min: 0,
      max: 5000,
      scale: 1,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'test_bit',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 21,
    mode: 'ro',
    name: '产测结果位',
    property: {
      min: 0,
      max: 5,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'voltage_coe',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 22,
    mode: 'ro',
    name: '电压校准系数',
    property: {
      min: 0,
      max: 1000000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'electric_coe',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 23,
    mode: 'ro',
    name: '电流校准系数',
    property: {
      min: 0,
      max: 1000000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'power_coe',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 24,
    mode: 'ro',
    name: '功率校准系数',
    property: {
      min: 0,
      max: 1000000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'electricity_coe',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    id: 25,
    mode: 'ro',
    name: '电量校准系数',
    property: {
      min: 0,
      max: 1000000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 736,
    canTrigger: false,
    code: 'relay_status',
    defaultRecommend: true,
    editPermission: false,
    executable: false,
    extContent: '',
    iconname: 'icon-zhuangtai',
    id: 38,
    mode: 'rw',
    name: '上电状态设置',
    property: {
      range: ['off', 'on', 'memory'],
      type: 'enum',
    },
    type: 'obj',
  },
] as const;
