export const defaultSchema = [
  {
    attr: 1040,
    canTrigger: true,
    code: 'switch_1',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 1,
    mode: 'rw',
    name: '开关1',
    property: { type: 'bool' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'switch_2',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 2,
    mode: 'rw',
    name: '开关2',
    property: { type: 'bool' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'switch_3',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 3,
    mode: 'rw',
    name: '开关3',
    property: { type: 'bool' },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'usb_switch_1',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 7,
    mode: 'rw',
    name: 'USB1开关',
    property: { type: 'bool' },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'usb_switch_2',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power2',
    id: 8,
    mode: 'rw',
    name: 'USB2开关',
    property: { type: 'bool' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'countdown_1',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time2',
    id: 9,
    mode: 'rw',
    name: '开关1倒计时',
    property: { unit: 's', min: 0, max: 86400, scale: 0, step: 1, type: 'value' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'countdown_2',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time2',
    id: 10,
    mode: 'rw',
    name: '开关2倒计时',
    property: { unit: 's', min: 0, max: 86400, scale: 0, step: 1, type: 'value' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'countdown_3',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time2',
    id: 11,
    mode: 'rw',
    name: '开关3倒计时',
    property: { unit: 's', min: 0, max: 86400, scale: 0, step: 1, type: 'value' },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'usb_countdown_1',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time3',
    id: 15,
    mode: 'rw',
    name: 'USB1倒计时',
    property: { unit: 's', min: 0, max: 86400, scale: 0, step: 1, type: 'value' },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'usb_countdown_2',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time3',
    id: 16,
    mode: 'rw',
    name: 'USB2倒计时',
    property: { unit: 's', min: 0, max: 86400, scale: 0, step: 1, type: 'value' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'add_ele',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-battery',
    id: 17,
    mode: 'rw',
    name: '增加电量',
    property: { unit: 'kwh', min: 0, max: 50000, scale: 3, step: 100, type: 'value' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'relay_status',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-zhuangtai',
    id: 38,
    mode: 'rw',
    name: '上电状态设置',
    property: { range: ['off', 'on', 'memory'], type: 'enum' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'light_mode',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'tcl_function_light',
    id: 40,
    mode: 'rw',
    name: '指示灯状态设置',
    property: { range: ['relay', 'pos', 'none'], type: 'enum' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'child_lock',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_lock',
    id: 41,
    mode: 'rw',
    name: '童锁开关',
    property: { type: 'bool' },
    type: 'obj',
  },
  {
    attr: 1024,
    canTrigger: true,
    code: 'cycle_time',
    defaultRecommend: false,
    editPermission: true,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_time',
    id: 42,
    mode: 'rw',
    name: '循环定时',
    property: { type: 'string', maxlen: 255 },
    type: 'obj',
  },
  {
    attr: 4096,
    canTrigger: true,
    code: 'work_state',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-zhuangtai',
    id: 101,
    mode: 'ro',
    name: '工作状态',
    property: { range: ['opening', 'closing'], type: 'enum' },
    type: 'obj',
  },
] as const;
