/**
 * 智能设备模型的 DP 功能点描述
 */
export const ipcSchema = [
  {
    id: 101,
    code: 'basic_indicator',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '状态指示灯',
  },
  {
    id: 102,
    code: 'ipc_flip',
    mode: 'rw',
    property: {
      range: ['flip_none', 'flip_horizontal_mirror', 'flip_vertical_mirror', 'flip_rotate_180'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '画面翻转方式',
  },
  {
    id: 103,
    code: 'basic_flip',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '画面翻转',
  },
  {
    id: 104,
    code: 'basic_osd',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '时间水印',
  },
  {
    id: 105,
    code: 'basic_private',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '隐私模式',
  },
  {
    id: 106,
    code: 'motion_sensitivity',
    mode: 'rw',
    property: {
      range: ['0', '1', '2'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '移动侦测灵敏度',
  },
  {
    id: 107,
    code: 'basic_wdr',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '宽动态范围模式',
  },
  {
    id: 108,
    code: 'basic_nightvision',
    mode: 'rw',
    property: {
      range: ['0', '1', '2'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '红外夜视',
  },
  {
    id: 109,
    code: 'sd_storge',
    mode: 'ro',
    property: {
      type: 'string',
      maxlen: 255,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '获取存储卡容量',
  },
  {
    id: 110,
    code: 'sd_status',
    mode: 'ro',
    property: {
      scale: 0,
      min: 1,
      type: 'value',
      max: 5,
      step: 1,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '存储卡状态',
  },
  {
    id: 111,
    code: 'sd_format',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '存储卡格式化',
  },
  {
    id: 112,
    code: 'sd_umount',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '卸载存储卡',
  },
  {
    id: 113,
    code: 'motion_record',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: 'SD卡录像模式',
  },
  {
    code: 'movement_detect_pic',
    id: 115,
    name: '检测到移动',
    type: 'raw',
    iconname: 'icon-setting',
    mode: 'ro',
  },
  {
    id: 116,
    code: 'ptz_stop',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '停止转动',
  },
  {
    id: 117,
    code: 'sd_format_state',
    mode: 'ro',
    property: {
      scale: 0,
      min: -20000,
      type: 'value',
      max: 200000,
      step: 1,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '格式化状态',
  },
  {
    id: 119,
    code: 'ptz_control',
    mode: 'rw',
    property: {
      range: ['1', '2', '3', '4', '5', '6', '7', '8'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '云台转动',
  },
  {
    id: 120,
    code: 'ipc_auto_siren',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-sound',
    type: 'obj',
    name: '触发蜂鸣器',
  },
  {
    id: 121,
    code: 'record_loop',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '循环录像',
  },
  {
    id: 122,
    code: 'ipc_wifi_switch',
    mode: 'rw',
    property: {
      type: 'string',
      maxlen: '255',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '切换Wifi',
  },
  {
    id: 123,
    code: 'ipc_sharp',
    mode: 'rw',
    property: {
      unit: '%',
      min: 0,
      scale: 0,
      step: 1,
      type: 'value',
      max: 100,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '画面锐度',
  },
  {
    id: 124,
    code: 'nightvision_mode',
    mode: 'rw',
    property: {
      range: ['auto', 'ir_mode', 'color_mode'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '夜视模式',
  },
  {
    id: 125,
    code: 'siren_sound',
    mode: 'rw',
    property: {
      range: [
        'item_1',
        'item_2',
        'item_3',
        'item_4',
        'item_5',
        'item_6',
        'item_7',
        'item_8',
        'item_9',
        'item_10',
      ],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '报警音',
  },
  {
    id: 126,
    code: 'battery_report_cap',
    mode: 'ro',
    property: {
      scale: 0,
      min: 0,
      type: 'value',
      max: 15,
      step: 1,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '电量精准上报能力',
  },
  {
    id: 132,
    code: 'ptz_calibration',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '云台校准',
  },
  {
    id: 133,
    code: 'motion_interval',
    mode: 'rw',
    property: {
      range: ['1', '3', '5'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '报警间歇',
  },
  {
    id: 134,
    code: 'motion_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '移动报警开关',
  },
  {
    id: 135,
    code: 'motion_timer_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '移动侦测-模式选择',
  },
  {
    id: 136,
    code: 'doorbell_active',
    mode: 'ro',
    property: {
      type: 'string',
      maxlen: 255,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '门铃-呼叫',
  },
  {
    id: 138,
    code: 'floodlight_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '灯',
  },
  {
    id: 139,
    code: 'decibel_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '声音侦测报警开关',
  },
  {
    id: 140,
    code: 'decibel_sensitivity',
    mode: 'rw',
    property: {
      range: ['0', '1'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '声音侦测灵敏度',
  },
  {
    id: 141,
    code: 'decibel_upload',
    mode: 'ro',
    property: {
      type: 'string',
      maxlen: 255,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '检测到声音',
  },
  {
    id: 142,
    code: 'sensor_temperature',
    mode: 'ro',
    property: {
      scale: 0,
      min: 0,
      type: 'value',
      max: 50,
      step: 1,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '温度',
  },
  {
    id: 143,
    code: 'sensor_humidity',
    mode: 'ro',
    property: {
      scale: 0,
      min: 0,
      type: 'value',
      max: 100,
      step: 1,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '湿度',
  },
  {
    id: 145,
    code: 'wireless_electricity',
    mode: 'ro',
    property: {
      unit: '%',
      min: 0,
      scale: 0,
      step: 1,
      type: 'value',
      max: 100,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '电量',
  },
  {
    id: 146,
    code: 'wireless_powermode',
    mode: 'ro',
    property: {
      range: ['0', '1'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '供电方式',
  },
  {
    id: 147,
    code: 'wireless_lowpower',
    mode: 'rw',
    property: {
      scale: 0,
      min: 10,
      type: 'value',
      max: 50,
      step: 1,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '低电报警',
  },
  {
    id: 148,
    code: 'accessory_lock',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '锁',
  },
  {
    id: 149,
    code: 'wireless_awake',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '唤醒状态',
  },
  {
    id: 150,
    code: 'record_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: 'SD卡录像开关',
  },
  {
    id: 151,
    code: 'record_mode',
    mode: 'rw',
    property: {
      range: ['1', '2'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '录像模式',
  },
  {
    id: 152,
    code: 'pir_switch',
    mode: 'rw',
    property: {
      range: ['0', '1', '2', '3', '4'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: 'PIR开关及灵敏度',
  },
  {
    id: 153,
    code: 'wireless_batterylock',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '电池锁',
  },
  {
    code: 'doorbell_pic',
    id: 154,
    name: '门铃图片',
    type: 'raw',
    iconname: 'icon-setting',
    mode: 'ro',
  },
  {
    id: 155,
    code: 'doorbell_ring_exist',
    mode: 'rw',
    property: {
      range: ['0', '1'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '铃铛配对',
  },
  {
    id: 156,
    code: 'chime_ring_tune',
    mode: 'rw',
    property: {
      range: ['1', '2', '3', '4'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '铃声',
  },
  {
    id: 157,
    code: 'chime_ring_volume',
    mode: 'rw',
    property: {
      scale: 0,
      min: 0,
      type: 'value',
      max: 100,
      step: 1,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '音量',
  },
  {
    id: 158,
    code: 'floodlight_lightness',
    mode: 'rw',
    property: {
      scale: 0,
      min: 1,
      type: 'value',
      max: 100,
      step: 1,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '灯光亮度',
  },
  {
    id: 159,
    code: 'siren_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '警笛',
  },
  {
    id: 160,
    code: 'basic_device_volume',
    mode: 'rw',
    property: {
      unit: '%',
      min: 1,
      scale: 0,
      step: 1,
      type: 'value',
      max: 100,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '音量控制',
  },
  {
    id: 161,
    code: 'motion_tracking',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '移动追踪开关',
  },
  {
    id: 162,
    code: 'device_restart',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '远程重启',
  },
  {
    id: 163,
    code: 'zoom_control',
    mode: 'rw',
    property: {
      range: ['0', '1'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '焦距控制',
  },
  {
    id: 164,
    code: 'zoom_stop',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '停止变焦',
  },
  {
    id: 165,
    code: 'chime_settings',
    mode: 'rw',
    property: {
      range: ['0', '1', '2', '3'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '铃铛模式设置',
  },
  {
    id: 166,
    code: 'chime_time',
    mode: 'rw',
    property: {
      unit: 's',
      min: 5,
      scale: 0,
      step: 1,
      type: 'value',
      max: 30,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '响铃时长',
  },
  {
    id: 167,
    code: 'cry_detection_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '哭声侦测',
  },
  {
    id: 168,
    code: 'motion_area_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '报警区域开关',
  },
  {
    id: 169,
    code: 'motion_area',
    mode: 'rw',
    property: {
      type: 'string',
      maxlen: 255,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '报警区域',
  },
  {
    id: 170,
    code: 'humanoid_filter',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '人形过滤',
  },
  {
    id: 171,
    code: 'flight_bright_mode',
    mode: 'rw',
    property: {
      range: ['0', '1'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '亮度模式',
  },
  {
    id: 172,
    code: 'flight_warn_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '警示开关',
  },
  {
    id: 173,
    code: 'flight_warn_time',
    mode: 'rw',
    property: {
      scale: 0,
      min: 1,
      type: 'value',
      max: 3600,
      step: 1,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '警示时间设置',
  },
  {
    id: 174,
    code: 'cruise_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '巡航开关',
  },
  {
    id: 175,
    code: 'cruise_mode',
    mode: 'rw',
    property: {
      range: ['0'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '巡航模式',
  },
  {
    id: 176,
    code: 'cruise_time_mode',
    mode: 'rw',
    property: {
      range: ['1'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '巡航时间模式',
  },
  {
    id: 177,
    code: 'cruise_time',
    mode: 'rw',
    property: {
      type: 'string',
      maxlen: 255,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '巡航时间',
  },
  {
    id: 178,
    code: 'memory_point_set',
    mode: 'rw',
    property: {
      type: 'string',
      maxlen: 255,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '收藏点',
  },
  {
    id: 179,
    code: 'cruise_status',
    mode: 'rw',
    property: {
      range: ['0', '1', '2'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '巡航状态',
  },
  {
    id: 180,
    code: 'basic_shimmer',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '微光全彩',
  },
  {
    id: 181,
    code: 'flight_pir_a',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: 'Pir 1',
  },
  {
    id: 182,
    code: 'flight_pir_b',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: 'Pir 2',
  },
  {
    id: 183,
    code: 'flight_pir_c',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: 'Pir 3',
  },
  {
    id: 184,
    code: 'pir_sensitivity',
    mode: 'rw',
    property: {
      range: ['0', '1', '2'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: 'pir灵敏度',
  },
  {
    code: 'alarm_message',
    id: 185,
    name: '告警消息上报',
    type: 'raw',
    iconname: 'icon-setting',
    mode: 'rw',
  },
  {
    id: 186,
    code: 'ai_fr_switch',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: 'AI人脸识别',
  },
  {
    id: 187,
    code: 'pet_detection',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '宠物检测',
  },
  {
    id: 188,
    code: 'basic_anti_flicker',
    mode: 'rw',
    property: {
      range: ['0', '1', '2'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '抗闪烁',
  },
  {
    id: 189,
    code: 'ipc_work_mode',
    mode: 'rw',
    property: {
      range: ['0', '1'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '工作模式',
  },
  {
    id: 190,
    code: 'ipc_preset_action',
    mode: 'wr',
    property: {
      range: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '收藏点联动',
  },
  {
    id: 192,
    code: 'ipc_contrast',
    mode: 'rw',
    property: {
      unit: '%',
      min: 0,
      scale: 0,
      step: 1,
      type: 'value',
      max: 100,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '画面对比度',
  },
  {
    id: 193,
    code: 'ipc_bright',
    mode: 'rw',
    property: {
      unit: '%',
      min: 0,
      scale: 0,
      step: 1,
      type: 'value',
      max: 100,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '画面亮度',
  },
  {
    id: 194,
    code: 'ipc_siren_duration',
    mode: 'rw',
    property: {
      unit: 's',
      min: 10,
      scale: 0,
      step: 10,
      type: 'value',
      max: 600,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '蜂鸣器时长',
  },
  {
    id: 195,
    code: 'ipc_siren_volume',
    mode: 'rw',
    property: {
      unit: '%',
      min: 0,
      scale: 0,
      step: 1,
      type: 'value',
      max: 100,
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '蜂鸣器音量',
  },
  {
    id: 197,
    code: 'ipc_mute_record',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: 'SD卡无声录制',
  },
  {
    id: 198,
    code: 'ipc_object_outline',
    mode: 'rw',
    property: {
      type: 'bool',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '智能画框',
  },
  {
    id: 199,
    code: 'ipc_preset_set',
    mode: 'rw',
    property: {
      range: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'],
      type: 'enum',
    },
    iconname: 'icon-setting',
    type: 'obj',
    name: '预设点设置',
  },
  {
    code: 'initiative_message',
    id: 212,
    name: '主动消息推送',
    mode: 'rw',
    type: 'raw',
  },
  {
    code: 'cruise_schedule',
    id: 231,
    name: '巡航计划',
    mode: 'rw',
    type: 'raw',
  },
  {
    code: 'cruise_stay_time',
    id: 232,
    property: {
      unit: '',
      min: 10,
      scale: 1,
      step: 10,
      type: 'value',
      max: 120,
    },
    name: '巡航单点停留时长',
    mode: 'rw',
    type: 'obj',
  },
  {
    code: 'light_color_control',
    id: 233,
    property: {
      type: 'string',
      maxlen: 255,
    },
    name: '自定义DP3彩光控制',
    mode: 'rw',
    type: 'obj',
  },
  {
    code: 'floodlight_mode',
    id: 234,
    property: {
      range: ['0', '1'],
      type: 'enum',
    },
    name: '自定义灯光模式',
    mode: 'rw',
    type: 'obj',
  },
  {
    code: 'floodlight_temp',
    id: 235,
    property: {
      unit: '%',
      min: 0,
      scale: 0,
      step: 1,
      type: 'value',
      max: 1000,
    },
    name: '自定义 DP2 色温调节',
    mode: 'rw',
    type: 'obj',
  },
  {
    code: 'colour_data',
    id: 236,
    property: {
      type: 'string',
      maxlen: 255,
    },
    name: '灯光模式数',
    mode: 'rw',
    type: 'obj',
  },
] as const;
