export const defaultSchema = [
  {
    attr: 0,
    canTrigger: true,
    code: 'charger_switch',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 101,
    mode: 'rw',
    name: '充电开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'discharge_switch',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 102,
    mode: 'rw',
    name: '放电开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'time_schedule',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '{}',
    id: 103,
    mode: 'rw',
    name: '时间段设置',
    type: 'raw',
  },
  {
    attr: 0,
    canTrigger: true,
    code: 'work_mode',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    id: 109,
    mode: 'rw',
    name: '工作模式',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
] as const;
