export const defaultSchema = [
  {
    attr: 641,
    canTrigger: true,
    code: 'switch_led',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_power',
    id: 20,
    mode: 'rw',
    name: '开关',
    property: {
      type: 'bool',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'work_mode',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mode',
    id: 21,
    mode: 'rw',
    name: '模式',
    property: {
      range: ['white', 'colour', 'scene', 'music'],
      type: 'enum',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'bright_value',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-liangdu1',
    id: 22,
    mode: 'rw',
    name: '亮度值',
    property: {
      min: 10,
      max: 1000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'temp_value',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_half',
    id: 23,
    mode: 'rw',
    name: '冷暖值',
    property: {
      min: 0,
      max: 1000,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'colour_data',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-yanse',
    id: 24,
    mode: 'rw',
    name: '彩光',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'scene_data',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-shoucang',
    id: 25,
    mode: 'rw',
    name: '场景',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'countdown',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-a_nav_timer',
    id: 26,
    mode: 'rw',
    name: '倒计时剩余时间',
    property: {
      unit: 's',
      min: 0,
      max: 86400,
      scale: 0,
      step: 1,
      type: 'value',
    },
    type: 'obj',
  },
  {
    attr: 128,
    canTrigger: true,
    code: 'music_data',
    defaultRecommend: false,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_mic',
    id: 27,
    mode: 'wr',
    name: '音乐灯',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
  {
    attr: 640,
    canTrigger: true,
    code: 'control_data',
    defaultRecommend: true,
    editPermission: false,
    executable: true,
    extContent: '',
    iconname: 'icon-dp_box2',
    id: 28,
    mode: 'wr',
    name: '调节',
    property: {
      type: 'string',
      maxlen: 255,
    },
    type: 'obj',
  },
] as const;
